## Data Loading - International Football Results 1872 to 2026

Loading in data using kaggle. Data used: https://www.kaggle.com/datasets/martj42/international-football-results-from-1872-to-2017/data

This dataset includes 49,393 results of international football matches starting from the very first official match in 1872 up to 2025. The matches range from FIFA World Cup to FIFI Wild Cup to regular friendly matches. The matches are strictly men's full internationals and the data does not include Olympic Games or matches where at least one of the teams was the nation's B-team, U-23 or a league select team.

**Goal of this notebook:** get from raw, messy match data to a clean
match-level table with a reliable win/draw/loss outcome per game — the
foundation that the Elo rating system (`elo_creation.ipynb`) and, later, the
Random Forest model are built on. The work here is exploratory; once an
approach is validated it gets promoted into
[`src/ml_world_cup_predictor/data_loading.py`](../src/ml_world_cup_predictor/data_loading.py).

In [ ]:
import shutil
import kagglehub
import pandas as pd
import numpy as np
import seaborn as sns
import datetime as dt
from pathlib import Path

DATA_DIRECTORY = Path("../data/international-football-results")

def get_data_path(data_directory:Path) -> Path:

    if data_directory.exists():
        path = data_directory
        print("Using cached dataset at:", path)
    else:
        download_path = kagglehub.dataset_download("martj42/international-football-results-from-1872-to-2017")
        data_directory.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(download_path, data_directory)
        path = data_directory
        print("Downloaded dataset to:", path)

    return path


def load_data(data_directory: Path) -> dict[str,pd.DataFrame]:
    frames = {file_path.stem : pd.read_csv(file_path) for file_path in sorted(data_directory.glob('*csv'))}

    for frame in frames.values():
        if 'date' in frame.columns:
            frame['date'] = pd.to_datetime(frame['date'],errors = 'coerce')
    
    return frames



frames = load_data(DATA_DIRECTORY)

results = frames['results']
shootouts = frames['shootouts']
goalscorers = frames['goalscorers']
former_names = frames['former_names']

`get_data_path`/`load_data` here are the scratch-pad version of this logic — they're later promoted into [`src/ml_world_cup_predictor/data_loading.py`](../src/ml_world_cup_predictor/data_loading.py) once validated, and reused from there in `elo_creation.ipynb`. The dataset is split across four CSVs (`results`, `shootouts`, `goalscorers`, `former_names`), downloaded once via `kagglehub` and cached locally so re-running the notebook doesn't re-download ~49k rows each time.

## Exploratory data review

Before doing any feature engineering, I wanted a consistent profile of every
column in each file: null rate, cardinality, summary statistics, and date
ranges. `dataset_review` runs this check generically across `results`,
`shootouts`, and `goalscorers` so the same exploration logic doesn't need to
be rewritten per file.

In [168]:
def string_column(df,col,cardinality_threshold):
    unique_values = df[col].nunique()
    print(f'Total Unique Values in {col} = {unique_values}')
    if unique_values <= cardinality_threshold:
        print(df[col].value_counts())
    else:
        print('\n\nTop 10 Most Frequent Values')
        print(df[col].value_counts().head(10))
        print('\n\nBottom 10 Most Frequent Values')
        print(df[col].value_counts().tail(20))

def number_column(df,col):
    print(f'\n\n=== Summary Statistic {col}===')
    print(f' Max = {df[col].max():.2f}')
    print(f' Mean = {df[col].mean():.2f}')
    #print(f' Mode = {df[col].mode():.2f}')
    print(f' Median = {df[col].median():.2f}')
    print(f' Min = {df[col].min():.2f}')

def date_column(df,col):

    df = df.copy()

    print(f'\n\n=== Summary Statistic {col}===')

    print(f'Earliest Date == {df[col].min()}')
    print(f'Latest Date == {df[col].max()}')

    df['month'] = df[col].dt.month
    df['year'] = df[col].dt.year
    

    print(df[col].value_counts().head(25))

    print('\n\n',df['year'].value_counts().head(25))

    print('\n\n',df['month'].value_counts())

    #print(cross_count.to_string)

def column_review(df,col,cardinality_threshold = 100):

    nulls = (df[col].isna()).sum()
    pct_null = nulls/(len(df[col]))
    print(f'{col} has {pct_null:.1%} nulls ({nulls} out of {len(df[col]):,})')

    if pd.api.types.is_string_dtype(df[col]):
        string_column(df,col,cardinality_threshold)
    
    if pd.api.types.is_any_real_numeric_dtype(df[col]) or pd.api.types.is_float_dtype(df[col]):
        number_column(df,col)

    if pd.api.types.is_datetime64_any_dtype(df[col]):
        date_column(df,col)
        
            


def dataset_review(df,cardinality_threshold = 100):

    
    print(f'Totals Rows = {len(df)}')
    print(f'Totals Columns = {len(df.columns)}') 
    print(f'Columns = {list(df.columns)}')
    print(df.dtypes)

    print('\n\n === Example Row ===')
    print(df.iloc[-1])

    for column in df.columns:

        column_review(df,column)

In [169]:
dataset_review(results)

Totals Rows = 49477
Totals Columns = 9
Columns = ['date', 'home_team', 'away_team', 'home_score', 'away_score', 'tournament', 'city', 'country', 'neutral']
date          datetime64[us]
home_team                str
away_team                str
home_score           float64
away_score           float64
tournament               str
city                     str
country                  str
neutral                 bool
dtype: object


 === Example Row ===
date          2026-06-27 00:00:00
home_team                 Croatia
away_team                   Ghana
home_score                    NaN
away_score                    NaN
tournament         FIFA World Cup
city                 Philadelphia
country             United States
neutral                      True
Name: 49476, dtype: object
date has 0.0% nulls (0 out of 49,477)


=== Summary Statistic date===
Earliest Date == 1872-11-30 00:00:00
Latest Date == 2026-06-27 00:00:00
date
2012-02-29    66
2016-03-29    64
2025-06-10    62
2025-03-25    61
2008-03-26    60
2014-03-05    59
2023-11-21    58
2012-11-14    56
2024-03-26    56
2011-11-11    55
2022-03-29    55
2011-10-11    54
2011-11-15    54
2008-09-06    53
2008-10-11    53
2011-09-02    53
2018-10-16    53
2024-09-10    53
2011-09-06    52
2023-10-17    52
2025-11-18    52
2010-08-11    51
2013-02-06    51
2015-11-17    51
2019-09-10    51
Name: count, dtype: int64


 year
2024    1231
2019    1149
2011    1119
2021    1115
2008    1101
2004    1079
2023    1054
2000    1040
2015    1039
2001    1032
2012    1025
2025    1002
2007     988
2022     970
2013     963
2003     947
2018     929
2009     925
2017     924
2016     920
1997     907
2010     863
2014     856
2006     842
1996     837
Name: count, dtype: int64


 month
6     7496
10    5626
11    5440
9     5389
3     5244
5     3532
7     3094
8     3019
12    2846
4     2715
2     2628
1     2448
Name: count, dtype: int64
home_team has 0.0% nulls (0 out of 49,477)
Total Unique Values in home_team = 327


Top 10 Most Frequent Values
home_team
Brazil           616
Argentina        608
Mexico           605
Germany          556
England          552
South Korea      552
France           540
Sweden           535
United States    502
Hungary          499
Name: count, dtype: int64


Bottom 10 Most Frequent Values
home_team
Elba Island                  2
Yoruba Nation                2
Biafra                       2
Mapuche                      2
Central Spain                1
Western Australia            1
Sark                         1
Chechnya                     1
Kurdistan                    1
Saint Pierre and Miquelon    1
Madrid                       1
Saugeais                     1
Franconia                    1
Seborga                      1
Ryūkyū                       1
Kabylia                      1
Aymara                       1
Ticino                       1
Hmong                        1
Marshall Islands             1
Name: count, dtype: int64
away_team has 0.0% nulls (0 out of 49,477)
Total Unique Values in away_team = 321


Top 10 Most Frequent Values
away_team
Uruguay        585
Sweden         569
England        541
Hungary        507
Paraguay       497
Germany        478
Argentina      464
Poland         463
Zambia         461
South Korea    458
Name: count, dtype: int64


Bottom 10 Most Frequent Values
away_team
Chechnya              2
Western Sahara        2
Franconia             2
Yorkshire             2
Maule Sur             2
Hmong                 2
Central Spain         1
Asturias              1
Manchukuo             1
Corsica               1
Cilento               1
Andalusia             1
Quebec                1
Surrey                1
Barawa                1
Parishes of Jersey    1
Biafra                1
Aymara                1
Ticino                1
Marshall Islands      1
Name: count, dtype: int64
home_score has 0.1% nulls (44 out of 49,477)


=== Summary Statistic home_score===
 Max = 31.00
 Mean = 1.76
 Median = 1.00
 Min = 0.00
away_score has 0.1% nulls (44 out of 49,477)


=== Summary Statistic away_score===
 Max = 21.00
 Mean = 1.18
 Median = 1.00
 Min = 0.00
tournament has 0.0% nulls (0 out of 49,477)
Total Unique Values in tournament = 200


Top 10 Most Frequent Values
tournament
Friendly                                18388
FIFA World Cup qualification             8771
UEFA Euro qualification                  2824
African Cup of Nations qualification     2327
FIFA World Cup                           1036
Copa América                              869
African Cup of Nations                    845
AFC Asian Cup qualification               829
UEFA Nations League                       658
CECAFA Cup                                620
Name: count, dtype: int64


Bottom 10 Most Frequent Values
tournament
Tri-Nations Series                  3
Outrigger Challenge Cup             3
Four Nations' Cup                   2
Cup of Ancient Civilizations        2
Atlantic Heritage Cup               2
Marianas Cup                        2
ASEAN Championship qualification    2
Mukuru 4 Nations                    2
Tri-Nations Cup                     2
Évence Coppée Trophy                1
Open International Championship     1
Real Madrid 75th Anniversary Cup    1
FIFA 75th Anniversary Cup           1
The Other Final                     1
TIFOCO Tournament                   1
Copa Confraternidad                 1
Benedikt Fontana Cup                1
ConIFA Challenger Cup               1
CONIFA World Cup qualification      1
South Asian Super Cup               1
Name: count, dtype: int64
city has 0.0% nulls (0 out of 49,477)
Total Unique Values in city = 2089


Top 10 Most Frequent Values
city
Kuala Lumpur    745
Bangkok         580
Doha            560
London          453
Budapest        437
Kuwait City     377
Montevideo      375
Vienna          365
Oslo            359
Glasgow         356
Name: count, dtype: int64


Bottom 10 Most Frequent Values
city
Fuladshahr          1
Décines-Charpieu    1
Tekkeköy            1
Yongin              1
Qingdao             1
Talatona            1
Gabala              1
Xiamen              1
Masazir             1
Old Road Town       1
Chattanooga         1
Pawtucket           1
Chapel Hill         1
Rendall             1
Stromness           1
Karviná             1
Tarija              1
Bo                  1
Pachuca             1
Auburn              1
Name: count, dtype: int64
country has 0.0% nulls (0 out of 49,477)
Total Unique Values in country = 269


Top 10 Most Frequent Values
country
United States    1559
France            932
Malaysia          830
England           773
Qatar             760
Thailand          723
Germany           685
Sweden            654
South Africa      611
Spain             609
Name: count, dtype: int64


Bottom 10 Most Frequent Values
country
Gold Coast                  6
Saarland                    6
Manchuria                   5
Yemen AR                    5
Monaco                      5
Northern Mariana Islands    5
French Somaliland           4
Nyasaland                   4
Timor-Leste                 4
Bohemia                     3
Mandatory Palestine         3
Belgian Congo               3
New Hebrides                3
Palau                       3
Bohemia and Moravia         2
Portuguese Guinea           2
Yemen DPR                   2
Greenland                   2
Mayotte                     2
Micronesia                  1
Name: count, dtype: int64
neutral has 0.0% nulls (0 out of 49,477)

In [170]:
dataset_review(shootouts)

Totals Rows = 678
Totals Columns = 5
Columns = ['date', 'home_team', 'away_team', 'winner', 'first_shooter']
date             datetime64[us]
home_team                   str
away_team                   str
winner                      str
first_shooter               str
dtype: object


 === Example Row ===
date             2026-06-06 00:00:00
home_team                  Lithuania
away_team                     Latvia
winner                     Lithuania
first_shooter              Lithuania
Name: 677, dtype: object
date has 0.0% nulls (0 out of 678)


=== Summary Statistic date===
Earliest Date == 1967-08-22 00:00:00
Latest Date == 2026-06-06 00:00:00
date
2016-06-03    5
2024-03-26    5
1986-10-01    4
2018-06-09    4
2021-07-06    4
2026-03-30    4
2018-06-03    3
2020-10-08    3
1973-06-14    2
1973-07-26    2
1984-03-14    2
1984-12-16    2
1985-12-25    2
1986-06-21    2
1989-04-23    2
1990-12-17    2
1991-01-21    2
1995-07-17    2
1995-12-02    2
1996-06-22    2
1996-06-26    2
1996-12-21    2
1998-01-31    2
1998-02-21    2
1998-05-29    2
Name: count, dtype: int64


 year
2019    27
2022    26
2002    24
2024    24
2016    23
2004    22
2000    21
1995    18
2018    18
2023    18
1996    17
1998    17
2015    17
2021    17
1984    16
2025    16
2005    15
2011    15
1988    14
1999    14
2003    14
2006    14
2026    14
1990    13
1993    13
Name: count, dtype: int64


 month
6     135
7     121
12     70
2      54
1      47
3      46
5      42
8      41
11     38
10     36
9      30
4      18
Name: count, dtype: int64
home_team has 0.0% nulls (0 out of 678)
Total Unique Values in home_team = 188


Top 10 Most Frequent Values
home_team
South Africa    18
Thailand        15
Zambia          15
Iran            15
Senegal         13
South Korea     12
Kenya           12
Argentina       12
Uruguay         12
Ivory Coast     10
Name: count, dtype: int64


Bottom 10 Most Frequent Values
home_team
Greenland                       1
Andorra                         1
Matabeleland                    1
Tibet                           1
Panjab                          1
South Ossetia                   1
Slovakia                        1
Scotland                        1
Serbia                          1
Saint Kitts and Nevis           1
Orkney                          1
Åland Islands                   1
Solomon Islands                 1
Georgia                         1
Turks and Caicos Islands        1
Venezuela                       1
United States Virgin Islands    1
Palestine                       1
Comoros                         1
Azerbaijan                      1
Name: count, dtype: int64
away_team has 0.0% nulls (0 out of 678)
Total Unique Values in away_team = 198


Top 10 Most Frequent Values
away_team
Egypt          16
Uganda         15
South Korea    13
Argentina      11
Cameroon       11
Mali           10
Malawi         10
Spain          10
Zambia         10
Italy          10
Name: count, dtype: int64


Bottom 10 Most Frequent Values
away_team
Djibouti                        1
Northern Ireland                1
Scotland                        1
Guadeloupe                      1
Moldova                         1
Tajikistan                      1
Grenada                         1
Puerto Rico                     1
Lebanon                         1
Greenland                       1
Falkland Islands                1
Anguilla                        1
United States Virgin Islands    1
Philippines                     1
Shetland                        1
Turks and Caicos Islands        1
Yemen                           1
Bosnia and Herzegovina          1
Comoros                         1
Finland                         1
Name: count, dtype: int64
winner has 0.0% nulls (0 out of 678)
Total Unique Values in winner = 183


Top 10 Most Frequent Values
winner
South Korea     15
Argentina       15
Egypt           15
Zambia          14
Thailand        13
South Africa    13
Iraq            11
Senegal         11
Indonesia       10
Kenya           10
Name: count, dtype: int64


Bottom 10 Most Frequent Values
winner
Basque Country                  1
Raetia                          1
New Zealand                     1
Felvidék                        1
Macau                           1
Western Isles                   1
Kabylia                         1
Panjab                          1
Northern Ireland                1
Equatorial Guinea               1
Guyana                          1
Puerto Rico                     1
Georgia                         1
Anguilla                        1
United States Virgin Islands    1
Vanuatu                         1
Palestine                       1
Comoros                         1
Azerbaijan                      1
Lithuania                       1
Name: count, dtype: int64
first_shooter has 62.2% nulls (422 out of 678)
Total Unique Values in first_shooter = 96
first_shooter
Colombia               11
Italy                  10
Brazil                  9
Argentina               8
Uruguay                 8
                       ..
Oman                    1
Yemen                   1
Comoros                 1
Azerbaijan              1
Trinidad and Tobago     1
Name: count, Length: 96, dtype: int64

In [171]:
dataset_review(goalscorers)

Totals Rows = 47690
Totals Columns = 8
Columns = ['date', 'home_team', 'away_team', 'team', 'scorer', 'minute', 'own_goal', 'penalty']
date         datetime64[us]
home_team               str
away_team               str
team                    str
scorer                  str
minute              float64
own_goal               bool
penalty                bool
dtype: object


 === Example Row ===
date            2026-06-18 00:00:00
home_team               Switzerland
away_team    Bosnia and Herzegovina
team         Bosnia and Herzegovina
scorer                 Ermin Mahmić
minute                         90.0
own_goal                      False
penalty                       False
Name: 47689, dtype: object
date has 0.0% nulls (0 out of 47,690)


=== Summary Statistic date===
Earliest Date == 1916-07-02 00:00:00
Latest Date == 2026-06-18 00:00:00
date
2011-10-11    145
2008-10-11    136
2008-09-06    135
2023-11-16    135
2004-09-08    132
2004-10-13    128
2011-09-02    125
2011-09-06    123
2011-10-07    122
2004-11-17    118
2012-10-16    118
2008-09-10    117
2015-11-17    116
2013-10-15    113
2012-09-11    111
2004-10-09    110
2019-10-10    109
2024-06-11    108
2011-11-15    107
2009-10-10    104
2015-10-13    104
2005-10-08    102
2013-09-06    102
2009-09-09    101
2012-10-12    101
Name: count, dtype: int64


 year
2021    2073
2001    1747
2025    1678
2004    1655
2024    1649
2019    1568
2015    1511
1997    1355
2011    1328
2008    1293
2000    1143
2023    1130
1993    1128
2013    1126
2005    1077
2007    1024
2016    1006
2017     985
1996     978
2009     965
2022     923
2012     869
2003     719
1989     625
1985     606
Name: count, dtype: int64


 month
6     9851
10    7835
9     6771
11    5369
3     4853
7     2892
1     2077
4     2041
5     1966
2     1635
12    1331
8     1069
Name: count, dtype: int64
home_team has 0.0% nulls (0 out of 47,690)
Total Unique Values in home_team = 220


Top 10 Most Frequent Values
home_team
Brazil         1048
Argentina      1019
Germany         844
Mexico          718
Netherlands     703
Spain           694
France          689
Chile           651
Belgium         633
Italy           617
Name: count, dtype: int64


Bottom 10 Most Frequent Values
home_team
Lesotho                     27
Central African Republic    26
British Virgin Islands      25
Guam                        25
Anguilla                    24
Guadeloupe                  23
Bhutan                      23
Cook Islands                22
Comoros                     22
São Tomé and Príncipe       19
Mongolia                    19
Martinique                  19
South Sudan                 17
Timor-Leste                 15
Somalia                     14
Eritrea                      7
French Guiana                6
Yemen DPR                    5
Saarland                     4
Vietnam Republic             4
Name: count, dtype: int64
away_team has 0.0% nulls (0 out of 47,690)
Total Unique Values in away_team = 220


Top 10 Most Frequent Values
away_team
Uruguay        803
Paraguay       679
Spain          598
Germany        579
Peru           577
Chile          561
Mexico         553
Netherlands    548
Luxembourg     545
Portugal       533
Name: count, dtype: int64


Bottom 10 Most Frequent Values
away_team
British Virgin Islands      48
Aruba                       46
Dominica                    46
Guadeloupe                  46
São Tomé and Príncipe       42
Comoros                     42
Somalia                     41
Turks and Caicos Islands    40
Montserrat                  38
Brunei                      37
Burundi                     36
Chad                        33
Vietnam Republic            31
Puerto Rico                 29
Cayman Islands              28
Eritrea                     17
Yemen DPR                   15
South Sudan                 14
Saarland                     8
French Guiana                3
Name: count, dtype: int64
team has 0.0% nulls (0 out of 47,690)
Total Unique Values in team = 220


Top 10 Most Frequent Values
team
Brazil         1076
Germany        1021
Argentina       982
Spain           940
Netherlands     898
Mexico          865
Uruguay         827
England         817
France          805
Italy           761
Name: count, dtype: int64


Bottom 10 Most Frequent Values
team
Mongolia                        11
Bhutan                          11
Guam                            11
São Tomé and Príncipe           10
American Samoa                  10
Vietnam Republic                 9
United States Virgin Islands     9
Cayman Islands                   9
British Virgin Islands           8
Seychelles                       8
Turks and Caicos Islands         7
Somalia                          6
Timor-Leste                      6
Brunei                           5
South Sudan                      5
Saarland                         4
Yemen DPR                        4
Eritrea                          4
Anguilla                         3
French Guiana                    2
Name: count, dtype: int64
scorer has 0.1% nulls (48 out of 47,690)
Total Unique Values in scorer = 15352


Top 10 Most Frequent Values
scorer
Cristiano Ronaldo      121
Harry Kane              71
Robert Lewandowski      69
Lionel Messi            66
Romelu Lukaku           64
Edin Džeko              58
Aleksandar Mitrović     52
Luis Suárez             51
Ali Daei                49
Miroslav Klose          48
Name: count, dtype: int64


Bottom 10 Most Frequent Values
scorer
Axel Tuanzebe            1
Gustaf Lagerbielke       1
Julián Quiñones          1
Jovo Lukić               1
Damián Bobadilla         1
Maurício                 1
Giovanni Reyna           1
Miro Muheim              1
Nico Schlotterbeck       1
Nathaniel Brown          1
Crysencio Summerville    1
Omar Rekik               1
Emam Ashour              1
Mohamed Hany             1
Abdulelah Al-Amri        1
Caleb Yirenkyi           1
Jaminton Campaz          1
Mohamed Manai            1
Michal Sadílek           1
Ermin Mahmić             1
Name: count, dtype: int64
minute has 0.5% nulls (256 out of 47,690)


=== Summary Statistic minute===
 Max = 122.00
 Mean = 50.06
 Median = 51.00
 Min = 1.00
own_goal has 0.0% nulls (0 out of 47,690)
penalty has 0.0% nulls (0 out of 47,690)

**Findings from the review:**
- `results` has 49,477 matches, with `home_score`/`away_score` null for 44
  rows — these are upcoming/unplayed fixtures (including the entire 2026
  World Cup draw), not data quality issues, and need to be separated from
  played matches before building any features.
- `tournament` has 200 distinct values, dominated by `Friendly` (18k+) and
  World Cup/continental qualifiers — this long tail matters later, since a
  friendly and a World Cup final shouldn't move a team's rating by the same
  amount.
- `shootouts` records the penalty-shootout winner separately from `results`,
  so a drawn match that was actually settled on penalties needs to be
  reconciled against this file to get the real W/L outcome.
- Team names aren't stable over time (e.g. historical entities, country
  renames) — `former_names` is needed to map historical squad names onto
  their current name before aggregating by team.

In [255]:
len(results[results['home_score'].isna()])

missing_match = {
    'date':dt.datetime(2024,10,27),
    'home_team':'Sierra Leone',
    'away_team':'Liberia',
    'home_score':1,
    'away_score':2,
    'tournament':'African Cup of Nations qualification',
    'city':'Monrovia',
    'country':'Liberia',
    'netural': False
}

row = pd.DataFrame(missing_match,index = [0])

results_new = pd.concat([results,row],ignore_index=True)

results_new = results_new.sort_values(by = 'date').reset_index()

results_new

,index,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,netural
0,0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False,NaN
1,1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False,NaN
2,2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False,NaN
3,3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False,NaN
4,4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
49473,49472,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True,NaN
49474,49473,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True,NaN
49475,49474,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True,NaN
49476,49475,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True,NaN
49477,49476,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True,NaN

**Data gap found:** a Sierra Leone vs Liberia African Cup of Nations
qualifier (2024-10-27) was missing from the source dataset entirely, despite
having been played, while genuinely upcoming/unplayed fixtures correctly
show `NaN` scores. Found by cross-checking results showing null scores
against fixture dates already in the past. The missing row is manually
appended here rather than dropped, so it isn't silently lost from any
team's match history or rating.

## Reconciling shootout results

`results` records penalty-shootout matches as draws on the scoreboard
(e.g. 1-1), with the actual winner only recoverable from the separate
`shootouts` file. To get a clean W/L/D outcome per match, the two files are
joined on `date` + `home_team` + `away_team`, and the shootout winner is
attached to the corresponding match. One shootout (Saare County vs Åland
Islands, 2011) doesn't have a matching row in `results` and is left
unmatched rather than guessed at.

In [ ]:


not_played = results_new[results_new['home_score'].isna()]
played = results_new[~results_new['home_score'].isna()]

played = played.assign(shootout_id = played[['date','home_team','away_team']].apply(
    lambda row: '_'.join([str(each) for each in row]), axis = 1
))

shootouts = shootouts.assign(shootout_id = shootouts[['date','home_team','away_team']].apply(
    lambda row: '_'.join([str(each) for each in row]), axis = 1
))

shootouts_ids = list(shootouts['shootout_id'].unique())

shootout_dict = pd.Series(shootouts['winner'].values, index = shootouts['shootout_id']).to_dict()

matches_with_shootouts = played[played['shootout_id'].isin(shootouts_ids)]

matches_with_shootouts = list(matches_with_shootouts['shootout_id'].unique())

print(len(shootouts_ids),len(matches_with_shootouts))

print(set(shootouts_ids)-set(matches_with_shootouts))


played['shootout_winner'] = played['shootout_id'].map(shootout_dict)

678 677
{'2011-06-29 00:00:00_Saare County_Åland Islands'}

In [257]:
played['goal_diff'] = np.abs(played['home_score']-played['away_score'])
played['year'] = played['date'].dt.year
played_long = played.melt(
    id_vars=['date','year','tournament'],
    value_vars=['home_team','away_team'],
    value_name='team'
)


wc_matches = played_long[(played_long['tournament'] == 'FIFA World Cup') & (played_long['year'] == 2026)]
wc_teams = wc_matches['team'].unique()
wc_former_names = former_names[former_names['current'].isin(wc_teams)]

name_map = dict(zip(wc_former_names['former'], wc_former_names['current']))

played['home_team'] = played['home_team'].replace(name_map)
played['away_team'] = played['away_team'].replace(name_map)

match_conditions = [
    played['home_score'] > played['away_score'],
    played['home_score'] < played['away_score'],
    played['shootout_winner'] == played['home_team'],
    played['shootout_winner'] == played['away_team']
]  

choices = ['W','L','W','L']
played['result'] = np.select(match_conditions,choices,default='D')

## Deriving match outcome and normalising team names

With shootout winners attached, each match gets a single `result` column
(`W`/`L`/`D` from the home team's perspective) and a `goal_diff` column,
which becomes the basis for outcome labels and Elo updates later. Team
names for the 2026 World Cup squads are also normalised against
`former_names`, so a team that competed under a former name in older
matches is still recognised as the same team when building its rating
history.

## Exploring "lineal champions"

As a sanity check on the cleaned `result` data (and a fun aside before the
core Elo work), `lineal_champions` tracks a boxing-style "champion" who
holds the title until beaten by a challenger they actually played. This is
purely exploratory — it isn't used as a model feature — but it's a good way
to spot-check that match results are being interpreted correctly across the
full history.

In [243]:

def lineal_champions(df):
    current_champion = None
    reign_log = []

    for row in df.itertuples(index = True,name='Match'):
        
        if current_champion is not None and current_champion not in (row.home_team, row.away_team):
            continue
        
        if row.result == 'W':
            challenger = row.home_team
        elif row.result == 'L':
            challenger = row.away_team
        else:
            continue

        if challenger != current_champion:
            reign_log.append({
                'date':row.date,
                'new_champion':challenger,
                'previous_champion':current_champion
            })
            current_champion = challenger

    reigns = pd.DataFrame(reign_log)
    reigns['reign_start'] = pd.to_datetime(reigns['date'])
    reigns['reign_end'] = reigns['reign_start'].shift(-1)
    reigns['reign_end'] = reigns['reign_end'].fillna(df['date'].max())
    reigns['days_reign'] = (reigns['reign_end'] - reigns['reign_start']).dt.days

    return reigns

In [ ]:


current_champion = None
reign_log = []

for row in played.itertuples(index = True,name='Match'):
    
    if current_champion is not None and current_champion not in (row.home_team, row.away_team):
        continue
    
    if row.result == 'W':
        challenger = row.home_team
    elif row.result == 'L':
        challenger = row.away_team
    else:
        continue

    if challenger != current_champion:
        reign_log.append({
            'date':row.date,
            'new_champion':challenger,
            'previous_champion':current_champion
        })
        current_champion = challenger

reigns = pd.DataFrame(reign_log)
reigns['reign_start'] = pd.to_datetime(reigns['date'])
reigns['reign_end'] = reigns['reign_start'].shift(-1)
reigns['reign_end'] = reigns['reign_end'].fillna(played['date'].max())
reigns['days_reign'] = (reigns['reign_end'] - reigns['reign_start']).dt.days

reigns

**Data quality issue found:** running the lineal champions check surfaced a
duplicate Zimbabwe vs Malawi result (row 29509) that doesn't match the
official record between the two sides — the duplicate is dropped before
re-running the check. This is a good example of why a derived sanity check
like this is worth keeping in the notebook even though it isn't a model
input: it catches row-level errors that column-level profiling (nulls,
ranges, cardinality) doesn't.

In [245]:
#def build_elo_trend_by_team(df,team,base = 1000,runway = 30):

zim_mask = (played['home_team'] == 'Zimbabwe') | ((played['away_team'] == 'Zimbabwe'))
mal_mask = (played['home_team'] == 'Malawi') | ((played['away_team'] == 'Malawi'))


def two_team_filter(df,team_a,team_b):

    team_a_mask = (df['home_team'] == team_a) | ((df['away_team'] == team_a))
    team_b_mask = (played['home_team'] == team_b) | ((played['away_team'] == team_b))

    df_new = df[team_a_mask & team_b_mask]

    return df_new

played[zim_mask & mal_mask]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,shootout_id,shootout_winner,goal_diff,year,result
7215,1967-11-12,Zimbabwe,Malawi,1.0,0.0,Friendly,Salisbury,Southern Rhodesia,False,1967-11-12 00:00:00_Zimbabwe_Malawi,NaN,1.0,1967,W
7601,1969-02-01,Malawi,Zimbabwe,2.0,2.0,Friendly,Zomba,Malawi,False,1969-02-01 00:00:00_Malawi_Zimbabwe,NaN,0.0,1969,D
7608,1969-02-08,Zimbabwe,Malawi,4.0,0.0,Friendly,Salisbury,Southern Rhodesia,False,1969-02-08 00:00:00_Zimbabwe_Malawi,NaN,4.0,1969,W
7611,1969-02-09,Zimbabwe,Malawi,1.0,1.0,Friendly,Salisbury,Southern Rhodesia,False,1969-02-09 00:00:00_Zimbabwe_Malawi,NaN,0.0,1969,D
7934,1969-12-01,Malawi,Zimbabwe,2.0,2.0,Friendly,Blantyre,Malawi,False,1969-12-01 00:00:00_Malawi_Zimbabwe,NaN,0.0,1969,D
12310,1980-07-06,Malawi,Zimbabwe,0.0,1.0,Friendly,Blantyre,Malawi,False,1980-07-06 00:00:00_Malawi_Zimbabwe,NaN,1.0,1980,L
12312,1980-07-08,Malawi,Zimbabwe,1.0,1.0,Friendly,Blantyre,Malawi,False,1980-07-08 00:00:00_Malawi_Zimbabwe,NaN,0.0,1980,D
12473,1980-10-26,Malawi,Zimbabwe,0.0,1.0,African Cup of Nations qualification,Blantyre,Malawi,False,1980-10-26 00:00:00_Malawi_Zimbabwe,NaN,1.0,1980,L
12501,1980-11-09,Zimbabwe,Malawi,1.0,1.0,African Cup of Nations qualification,Salisbury,Zimbabwe,False,1980-11-09 00:00:00_Zimbabwe_Malawi,NaN,0.0,1980,D
12730,1981-04-20,Zimbabwe,Malawi,4.0,0.0,Friendly,Bulawayo,Zimbabwe,False,1981-04-20 00:00:00_Zimbabwe_Malawi,NaN,4.0,1981,W
12854,1981-07-10,Malawi,Zimbabwe,2.0,0.0,Friendly,Blantyre,Malawi,False,1981-07-10 00:00:00_Malawi_Zimbabwe,NaN,2.0,1981,W
12929,1981-09-04,Malawi,Zimbabwe,1.0,2.0,Friendly,Mbabane,Swaziland,True,1981-09-04 00:00:00_Malawi_Zimbabwe,NaN,1.0,1981,L
13396,1982-09-12,Malawi,Zimbabwe,2.0,0.0,African Cup of Nations qualification,Lilongwe,Malawi,False,1982-09-12 00:00:00_Malawi_Zimbabwe,NaN,2.0,1982,W
13412,1982-10-03,Zimbabwe,Malawi,0.0,2.0,African Cup of Nations qualification,Harare,Zimbabwe,False,1982-10-03 00:00:00_Zimbabwe_Malawi,NaN,2.0,1982,L
13456,1982-11-16,Malawi,Zimbabwe,1.0,1.0,CECAFA Cup,Kampala,Uganda,True,1982-11-16 00:00:00_Malawi_Zimbabwe,NaN,0.0,1982,D
13729,1983-07-06,Malawi,Zimbabwe,0.0,0.0,Friendly,Blantyre,Malawi,False,1983-07-06 00:00:00_Malawi_Zimbabwe,NaN,0.0,1983,D
13730,1983-07-08,Malawi,Zimbabwe,1.0,0.0,Friendly,Blantyre,Malawi,False,1983-07-08 00:00:00_Malawi_Zimbabwe,NaN,1.0,1983,W
13920,1983-11-13,Malawi,Zimbabwe,0.0,1.0,CECAFA Cup,Mombasa,Kenya,True,1983-11-13 00:00:00_Malawi_Zimbabwe,NaN,1.0,1983,L
14423,1984-11-17,Malawi,Zimbabwe,3.0,0.0,Friendly,Lilongwe,Malawi,False,1984-11-17 00:00:00_Malawi_Zimbabwe,NaN,3.0,1984,W
14427,1984-11-19,Malawi,Zimbabwe,1.0,0.0,Friendly,Blantyre,Malawi,False,1984-11-19 00:00:00_Malawi_Zimbabwe,NaN,1.0,1984,W
14796,1985-05-02,Zimbabwe,Malawi,1.0,3.0,Friendly,Harare,Zimbabwe,False,1985-05-02 00:00:00_Zimbabwe_Malawi,NaN,2.0,1985,L
15009,1985-10-11,Zimbabwe,Malawi,1.0,0.0,CECAFA Cup,Bulawayo,Zimbabwe,False,1985-10-11 00:00:00_Zimbabwe_Malawi,NaN,1.0,1985,W
15718,1987-06-13,Malawi,Zimbabwe,1.0,4.0,Friendly,Lilongwe,Malawi,False,1987-06-13 00:00:00_Malawi_Zimbabwe,NaN,3.0,1987,L
15723,1987-06-14,Malawi,Zimbabwe,2.0,1.0,Friendly,Blantyre,Malawi,False,1987-06-14 00:00:00_Malawi_Zimbabwe,NaN,1.0,1987,W
15916,1987-12-13,Malawi,Zimbabwe,1.0,1.0,CECAFA Cup,Addis Ababa,Ethiopia,True,1987-12-13 00:00:00_Malawi_Zimbabwe,Zimbabwe,0.0,1987,L
17571,1990-12-09,Malawi,Zimbabwe,0.0,0.0,CECAFA Cup,Zanzibar City,Zanzibar,True,1990-12-09 00:00:00_Malawi_Zimbabwe,NaN,0.0,1990,D
17689,1991-04-14,Zimbabwe,Malawi,4.0,0.0,African Cup of Nations qualification,Harare,Zimbabwe,False,1991-04-14 00:00:00_Zimbabwe_Malawi,NaN,4.0,1991,W
17910,1991-07-27,Malawi,Zimbabwe,2.0,2.0,African Cup of Nations qualification,Zomba,Malawi,False,1991-07-27 00:00:00_Malawi_Zimbabwe,NaN,0.0,1991,D
18352,1992-07-06,Malawi,Zimbabwe,0.0,0.0,Friendly,Blantyre,Malawi,False,1992-07-06 00:00:00_Malawi_Zimbabwe,NaN,0.0,1992,D
18355,1992-07-08,Malawi,Zimbabwe,0.0,0.0,Friendly,Blantyre,Malawi,False,1992-07-08 00:00:00_Malawi_Zimbabwe,NaN,0.0,1992,D
18606,1992-11-07,Zimbabwe,Malawi,0.0,1.0,Friendly,Harare,Zimbabwe,False,1992-11-07 00:00:00_Zimbabwe_Malawi,NaN,1.0,1992,L
18615,1992-11-09,Zimbabwe,Malawi,4.0,1.0,Friendly,Harare,Zimbabwe,False,1992-11-09 00:00:00_Zimbabwe_Malawi,NaN,3.0,1992,W
19980,1994-10-15,Malawi,Zimbabwe,3.0,1.0,African Cup of Nations qualification,Blantyre,Malawi,False,1994-10-15 00:00:00_Malawi_Zimbabwe,NaN,2.0,1994,W
20273,1995-04-23,Zimbabwe,Malawi,1.0,1.0,African Cup of Nations qualification,Harare,Zimbabwe,False,1995-04-23 00:00:00_Zimbabwe_Malawi,NaN,0.0,1995,D
22525,1998-01-03,Malawi,Zimbabwe,1.0,0.0,Friendly,Blantyre,Malawi,False,1998-01-03 00:00:00_Malawi_Zimbabwe,NaN,1.0,1998,W
22529,1998-01-04,Malawi,Zimbabwe,0.0,2.0,Friendly,Lilongwe,Malawi,False,1998-01-04 00:00:00_Malawi_Zimbabwe,NaN,2.0,1998,L
22905,1998-07-18,Malawi,Zimbabwe,1.0,0.0,Friendly,Blantyre,Malawi,False,1998-07-18 00:00:00_Malawi_Zimbabwe,NaN,1.0,1998,W
22909,1998-07-20,Malawi,Zimbabwe,0.0,0.0,Friendly,Lilongwe,Malawi,False,1998-07-20 00:00:00_Malawi_Zimbabwe,NaN,0.0,1998,D
23301,1999-01-23,Zimbabwe,Malawi,3.0,0.0,Friendly,Bulawayo,Zimbabwe,False,1999-01-23 00:00:00_Zimbabwe_Malawi,NaN,3.0,1999,W
23310,1999-01-24,Zimbabwe,Malawi,1.0,0.0,Friendly,Harare,Zimbabwe,False,1999-01-24 00:00:00_Zimbabwe_Malawi,NaN,1.0,1999,W
25301,2001-03-11,Zimbabwe,Malawi,2.0,0.0,FIFA World Cup qualification,Harare,Zimbabwe,False,2001-03-11 00:00:00_Zimbabwe_Malawi,NaN,2.0,2001,W
25826,2001-07-28,Malawi,Zimbabwe,0.0,1.0,FIFA World Cup qualification,Blantyre,Malawi,False,2001-07-28 00:00:00_Malawi_Zimbabwe,NaN,1.0,2001,L
25891,2001-08-25,Malawi,Zimbabwe,0.0,2.0,COSAFA Cup,Blantyre,Malawi,False,2001-08-25 00:00:00_Malawi_Zimbabwe,NaN,2.0,2001,L
26519,2002-07-07,Malawi,Zimbabwe,3.0,2.0,Friendly,Blantyre,Malawi,False,2002-07-07 00:00:00_Malawi_Zimbabwe,NaN,1.0,2002,W
26524,2002-07-08,Malawi,Zimbabwe,2.0,2.0,Friendly,Lilongwe,Malawi,False,2002-07-08 00:00:00_Malawi_Zimbabwe,NaN,0.0,2002,D
27025,2003-03-16,Zimbabwe,Malawi,0.0,0.0,Friendly,Harare,Zimbabwe,False,2003-03-16 00:00:00_Zimbabwe_Malawi,NaN,0.0,2003,D
27585,2003-09-27,Malawi,Zimbabwe,1.0,2.0,COSAFA Cup,Blantyre,Malawi,False,2003-09-27 00:00:00_Malawi_Zimbabwe,NaN,1.0,2003,L
27594,2003-10-05,Zimbabwe,Malawi,2.0,0.0,COSAFA Cup,Harare,Zimbabwe,False,2003-10-05 00:00:00_Zimbabwe_Malawi,NaN,2.0,2003,W
29037,2005-02-27,Malawi,Zimbabwe,2.0,1.0,Friendly,Blantyre,Malawi,False,2005-02-27 00:00:00_Malawi_Zimbabwe,NaN,1.0,2005,W
29509,2005-09-24,Malawi,Zimbabwe,2.0,0.0,Friendly,Maputo,Mozambique,True,2005-09-24 00:00:00_Malawi_Zimbabwe,NaN,2.0,2005,W
30087,2006-06-24,Malawi,Zimbabwe,1.0,1.0,Friendly,Maputo,Mozambique,True,2006-06-24 00:00:00_Malawi_Zimbabwe,NaN,0.0,2006,D
30350,2006-10-07,Malawi,Zimbabwe,1.0,0.0,African Cup of Nations qualification,Blantyre,Malawi,False,2006-10-07 00:00:00_Malawi_Zimbabwe,NaN,1.0,2006,W
31260,2007-09-09,Zimbabwe,Malawi,3.0,1.0,African Cup of Nations qualification,Bulawayo,Zimbabwe,False,2007-09-09 00:00:00_Zimbabwe_Malawi,NaN,2.0,2007,W
33730,2010-03-03,Zimbabwe,Malawi,2.0,1.0,Friendly,Harare,Zimbabwe,False,2010-03-03 00:00:00_Zimbabwe_Malawi,NaN,1.0,2010,W
36899,2013-05-25,Malawi,Zimbabwe,1.0,1.0,Friendly,Blantyre,Malawi,False,2013-05-25 00:00:00_Malawi_Zimbabwe,NaN,0.0,2013,D
37100,2013-07-13,Zimbabwe,Malawi,1.0,1.0,COSAFA Cup,Lusaka,Zambia,True,2013-07-13 00:00:00_Zimbabwe_Malawi,Zimbabwe,0.0,2013,W
37616,2014-03-05,Malawi,Zimbabwe,1.0,4.0,Friendly,Blantyre,Malawi,False,2014-03-05 00:00:00_Malawi_Zimbabwe,NaN,3.0,2014,L
38794,2015-06-13,Malawi,Zimbabwe,1.0,2.0,African Cup of Nations qualification,Blantyre,Malawi,False,2015-06-13 00:00:00_Malawi_Zimbabwe,NaN,1.0,2015,L
39820,2016-06-05,Zimbabwe,Malawi,3.0,0.0,African Cup of Nations qualification,Harare,Zimbabwe,False,2016-06-05 00:00:00_Zimbabwe_Malawi,NaN,3.0,2016,W
43513,2020-10-11,Malawi,Zimbabwe,0.0,0.0,Friendly,Blantyre,Malawi,False,2020-10-11 00:00:00_Malawi_Zimbabwe,NaN,0.0,2020,D
44232,2021-07-09,Malawi,Zimbabwe,2.0,2.0,COSAFA Cup,Port Elizabeth,South Africa,True,2021-07-09 00:00:00_Malawi_Zimbabwe,NaN,0.0,2021,D
44860,2022-01-14,Malawi,Zimbabwe,2.0,1.0,African Cup of Nations,Bafoussam,Cameroon,True,2022-01-14 00:00:00_Malawi_Zimbabwe,NaN,1.0,2022,W

In [ ]:
played_zimbabwe_fix = played.drop(29509)

missing_match = {
    'date':dt.datetime(2024,10,27),
    'home_team':'Sierra Leone',
    'away_team':'Liberia',
    'home_score':1,
    'away_score':2,
    'tournament':'African Cup of Nations qualification',
    'city':'Monrovia',
    'country':'Liberia',
    'netural': False
}

reign = lineal_champions(played_zimbabwe_fix)

new_champion
Scotland               12997
England                 7497
Argentina               2895
Northern Ireland        2709
France                  2343
Netherlands             2193
Russia                  2096
Wales                   1820
Uruguay                 1694
Brazil                  1581
Germany                 1420
Chile                   1418
Colombia                1348
Italy                   1334
Spain                   1216
Switzerland             1181
Sweden                  1025
Hungary                 1008
Peru                     960
Austria                  816
Croatia                  658
Paraguay                 461
Bulgaria                 422
Czechoslovakia           391
Israel                   336
Portugal                 314
Mexico                   312
Angola                   310
Greece                   308
Czech Republic           257
Mozambique               216
Bolivia                  214
Algeria                  205
Kosovo                   204
Ivory Coast              203
Belgium                  201
Guadeloupe               186
Zimbabwe                 182
Costa Rica               160
Republic of Ireland      122
Serbia                   116
Denmark                   97
Romania                   81
Venezuela                 80
Turkey                    74
Finland                   56
Poland                    41
Cuba                      38
Ecuador                   33
Panama                    29
Yugoslavia                28
Nigeria                   22
Liberia                   21
United States             16
Sierra Leone              12
Australia                 10
South Korea                8
Curaçao                    4
North Macedonia            4
Lesotho                    1
Name: days_reign, dtype: int64

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
6824,1966-11-12,Sierra Leone,Liberia,1.0,1.0,Friendly,Freetown,Sierra Leone,False
6832,1966-11-19,Liberia,Sierra Leone,2.0,0.0,Friendly,Monrovia,Liberia,False
10520,1976-04-25,Sierra Leone,Liberia,1.0,0.0,Friendly,Freetown,Sierra Leone,False
13440,1982-11-07,Liberia,Sierra Leone,1.0,0.0,Friendly,Monrovia,Liberia,False
15488,1986-10-05,Sierra Leone,Liberia,2.0,1.0,African Cup of Nations qualification,Freetown,Sierra Leone,False
15511,1986-10-19,Liberia,Sierra Leone,1.0,1.0,African Cup of Nations qualification,Monrovia,Liberia,False
16435,1988-11-26,Liberia,Sierra Leone,0.0,0.0,Friendly,Monrovia,Liberia,False
20761,1995-12-17,Sierra Leone,Liberia,1.0,0.0,Friendly,Freetown,Sierra Leone,False
20785,1996-01-06,Sierra Leone,Liberia,2.0,1.0,Friendly,Freetown,Sierra Leone,False
25239,2001-02-25,Liberia,Sierra Leone,1.0,0.0,FIFA World Cup qualification,Paynesville,Liberia,False
25792,2001-07-14,Sierra Leone,Liberia,0.0,1.0,FIFA World Cup qualification,Freetown,Sierra Leone,False
29265,2005-06-10,Sierra Leone,Liberia,2.0,0.0,Friendly,Freetown,Sierra Leone,False
31806,2008-04-30,Liberia,Sierra Leone,3.0,1.0,Friendly,Paynesville,Liberia,False
41704,2018-07-22,Liberia,Sierra Leone,0.0,0.0,Friendly,Monrovia,Liberia,False
42819,2019-09-04,Liberia,Sierra Leone,3.0,1.0,FIFA World Cup qualification,Monrovia,Liberia,False
42920,2019-09-08,Sierra Leone,Liberia,1.0,0.0,FIFA World Cup qualification,Freetown,Sierra Leone,False
45055,2022-03-27,Liberia,Sierra Leone,0.0,1.0,Friendly,Antalya,Turkey,True
49350,2026-06-06,Sierra Leone,Liberia,1.0,0.0,Friendly,Bo,Sierra Leone,False
49399,2026-06-09,Liberia,Sierra Leone,3.0,1.0,Friendly,Monrovia,Liberia,False